#!/bin/bash

python utils/viz/visualizer.py \
    --t_max 1000 \
    --n_epochs 20 \
    --verbose \
    --model "u-net" \
    --dataset "CIFAR10" \
    --batch_size 8 \
    --num_workers 4 \
    --validation \
    --test \
    --val_ratio 0.05 \
    --seed 42 \
    --num_trials 1 \
    --learning_rate 1e-5 \
    --dropout 0.2 \
    --optimizer_name "adam" \
    --grad_clip 0.0 \
    --patience 5 \
    --activation "silu" \
    --time_base_dim 16 \
    --time_hidden 32 \
    --time_output_dim 16 \
    --init_scheme "auto" \
    --base_channels 16 \
    --channel_mults 1,2,2 \
    --num_res_blocks 1 \
    --upsample "nearest_conv" \
    --groups 8 \
    --num_res_blocks_in_bottleneck 1 \
    --norm_2d "group" \
    --stem_kernel 3 \
    --head_kernel 3 \
    --downsample "stride" \
    --log_dir "./logs" \
    --checkpoint_dir "./checkpoints" \
    --save_frequency 10 \
    --output_dir "./outputs" \
    --path_to_weights "./checkpoints/CIFAR10_u-net_experiment/version_0/best.pth" \
    --fps 10
